### ISSUE TITLE
Uncaught TypeError: Cannot read property 'exec' of undefined

### ISSUE THREAD

**Issue by coopermaruyama** [nikhilkalige/docblockr#109]
[Enter steps to reproduce below:]
1. Was working on this file:

``` coffee
Template.NoGuessworkChapterContent.helpers
  currentChapter: ->
    "NGChapter#{@number}"
  ###*
   * Chapters that are to be shown in production
   *
   * @type {Array}
  ###
  publishedChapters: [1,2,3,4]
  ###*
  sidenavData: ->
    _.each @publishedChapters, (_chapter, index, _chapters) ->
      chapterName = "NGChapters#{_chapter}"
      html = Template[chapterName].renderFunction().value
      $chapter = $('<body'+html+'</body>')
      $sections = $chapter.find('> h2, > h3')
      sectionTitles = _.map $sections, ($node) -> return $node.text()
      return sectionTitles
```
1. Had my cursor on line 10, after the `###*` before `sideNavData: ->`
2. click `enter' to create a docblock
3. got this error. Happens often. Note that it didn't happen on the `publishedChapters` directly above.

**Atom Version**: 0.201.0
**System**: Mac OS X 10.10.1
**Thrown From**: [docblockr](https://github.com/nikhilkalige/docblockr) package, v0.7.2
### Stack Trace

Uncaught TypeError: Cannot read property 'exec' of undefined

```
At /Users/cooperm/.atom/packages/docblockr/lib/docsparser.js:311

TypeError: Cannot read property 'exec' of undefined
  at check_match (/Users/cooperm/.atom/packages/docblockr/lib/docsparser.js:311:30)
  at Array.filter (native)
  at DocsParser.get_matching_notations (/Users/cooperm/.atom/packages/docblockr/lib/docsparser.js:314:54)
  at DocsParser.guess_type_from_name (/Users/cooperm/.atom/packages/docblockr/lib/docsparser.js:286:24)
  at DocsParser.get_function_return_type (/Users/cooperm/.atom/packages/docblockr/lib/docsparser.js:209:18)
  at DocsParser.format_function (/Users/cooperm/.atom/packages/docblockr/lib/docsparser.js:148:25)
  at DocsParser.parse (/Users/cooperm/.atom/packages/docblockr/lib/docsparser.js:44:37)
  at DocBlockrAtom.module.exports.DocBlockrAtom.parse_command (/Users/cooperm/.atom/packages/docblockr/lib/docblockr-worker.js:279:29)
  at atom-workspace.<anonymous> (/Users/cooperm/.atom/packages/docblockr/lib/docblockr-worker.js:75:16)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:238:29)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
  at CommandPaletteView.module.exports.CommandPaletteView.confirmed (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/command-palette/lib/command-palette-view.js:159:32)
  at CommandPaletteView.module.exports.SelectListView.confirmSelection (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:338:21)
  at space-pen-div.atom.commands.add.core:confirm (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:109:19)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:238:29)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:519:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:354:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:178:20)

```
### Commands

```
     -0:58.1.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:58.1.0 coffeedocs:generate (atom-text-editor.editor)
     -0:45.1.0 core:undo (atom-text-editor.editor.is-focused)
     -0:44.3.0 editor:delete-to-beginning-of-line (atom-text-editor.editor.is-focused)
     -0:44.1.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:43.5.0 core:move-down (atom-text-editor.editor.is-focused)
     -0:40.4.0 command-palette:toggle (atom-text-editor.editor.is-focused)
 26x -0:36.4.0 core:move-down (atom-text-editor.editor.mini.is-focused)
  2x -0:24.9.0 core:move-up (atom-text-editor.editor.mini.is-focused)
  4x -0:23.7.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -0:14.7.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:14.7.0 docblockr:reparse (atom-text-editor.editor)
     -0:11 command-palette:toggle (atom-text-editor.editor.is-focused)
  5x -0:08.6.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -0:06.7.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:06.7.0 docblockr:parse-enter (atom-text-editor.editor)
```
### Config

``` json
{
  "core": {
    "ignoredNames": [
      ".meteor",
      ".git",
      ".DS_Store"
    ],
    "disabledPackages": [
      "git-grep",
      "atom-prettify",
      "resize-panes",
      "themed-settings",
      "autocomplete-paths",
      "tree-view-filter",
      "letter-spacing",
      "atomatigit",
      "meteor-helper",
      "stacktrace",
      "save-session",
      "notebook",
      "scope-inspector",
      "tabs",
      "tree-view",
      "git-wip",
      "linter-eslint",
      "atom-jade",
      "vim-mode",
      "atom-lint",
      "atom-angularjs",
      "atom-bootstrap3",
      "atom-coffee-repl",
      "visual-bell",
      "view-tail-large-files",
      "atom-package-blank",
      "autocomplete-glsl",
      "term2",
      "coffee-porter",
      "figlet",
      "language-babel",
      "angularjs",
      "linter-handlebars",
      "sass-autocompile",
      "remote-atom",
      "remote-edit",
      "web-browser",
      "language-make",
      "background-tips",
      "exception-reporting",
      "language-clojure",
      "spell-check",
      "welcome",
      "autosave",
      "ever-notedown"
    ],
    "projectHome": "/Users/cooperm/sites",
    "audioBeep": false,
    "themes": [
      "one-dark-ui",
      "apathy-theme"
    ]
  },
  "docblockr": {
    "auto_add_method_tag": true,
    "per_section_indent": true,
    "lower_case_primitives": true,
    "short_primitives": true,
    "notation_map": [
      "{\"regex\":\"data$\"",
      "\"type\":\"object\"}"
    ],
    "spacer_between_sections": true
  }
}
```
### Installed Packages

``` coffee
# User
ScssBundle, v0.5.0
apathy-theme, v1.1.14
atom-handlebars, v0.5.0
atom-jasmine, v0.5.0
atom-runner, v2.3.0
coffee-compile, v0.15.0
coffee-refactor, v0.6.2
coffeedocs, v0.8.2
color-picker, v1.7.0
cucumber, v0.5.0
docblockr, v0.7.2
emmet, v2.3.10
file-icons, v1.5.5
file-types, v0.3.0
gist-it, v0.7.0
git-diff-details, v0.18.0
git-log, v0.3.0
js-refactor, v0.3.0
jsdoc, v0.9.0
language-jade, v0.4.0
language-javascript-semantic, v0.1.0
language-js-specs, v0.1.0
language-log, v0.4.0
language-spacebars, v0.2.2
linter, v0.12.6
linter-coffeelint, v0.2.3
linter-jscs, v1.12.0
linter-scss-lint, v1.0.4
meteor-api, v2.19.0
minimap, v4.9.0
package-sync, v0.2.0
pigments, v0.3.1
project-manager, v1.15.7
refactor, v0.4.1
script, v2.23.0
sublime-tabs, v0.5.6
syntax-settings, v0.7.1
tree-ignore, v0.2.5

# Dev
apathy-theme, v1.1.14
```

**Comment by NikhilKalige** [comment]
I believe you are using coffeescript. I tried your code and this is what i get. I am on v0.200 so let me check again after I get an update
```
Template.NoGuessworkChapterContent.helpers
  currentChapter: ->
    "NGChapter#{@number}"
  ###*
   * [publishedChapters description]
   * @type {Array}
  ###
  publishedChapters: [1,2,3,4]
  ###*
   * [sidenavData description]
   * @return {[type]} [description]
  ###
  sidenavData: ->
    _.each @publishedChapters, (_chapter, index, _chapters) ->
      chapterName = "NGChapters#{_chapter}"
      html = Template[chapterName].renderFunction().value
      $chapter = $('<body'+html+'</body>')
      $sections = $chapter.find('> h2, > h3')
      sectionTitles = _.map $sections, ($node) -> return $node.text()
      return sectionTitles
```

**Comment by coopermaruyama** [comment]
Yeah, isn't docblockr supposed to work with Coffeescript? It's worked for me usually on Coffee. I'm getting the same error in JS, too - on this block for example:

```js
/**
Convertify.utils.getHelper = function(template, helperName) {
  if (! template instanceof Template) {
    throw new Error('template arg needs to be an instance of `Template`');
  }
  if (! typeof(helperName) == "string") {
    throw new Error('helperName needs to be a string.');
  }
  return Blaze._getTemplateHelper(template, helperName);
}
```

---

## Stacktrace

**Atom Version**: 0.201.0
**System**: Mac OS X 10.10.1
**Thrown From**: [docblockr](https://github.com/nikhilkalige/docblockr) package, v0.7.2


### Stack Trace

Uncaught TypeError: Cannot read property 'exec' of undefined

```
At /Users/cooperm/.atom/packages/docblockr/lib/docsparser.js:311

TypeError: Cannot read property 'exec' of undefined
  at check_match (/Users/cooperm/.atom/packages/docblockr/lib/docsparser.js:311:30)
  at Array.filter (native)
  at DocsParser.get_matching_notations (/Users/cooperm/.atom/packages/docblockr/lib/docsparser.js:314:54)
  at DocsParser.guess_type_from_name (/Users/cooperm/.atom/packages/docblockr/lib/docsparser.js:286:24)
  at DocsParser.get_type_info (/Users/cooperm/.atom/packages/docblockr/lib/docsparser.js:99:56)
  at DocsParser.format_function (/Users/cooperm/.atom/packages/docblockr/lib/docsparser.js:135:30)
  at DocsParser.parse (/Users/cooperm/.atom/packages/docblockr/lib/docsparser.js:44:37)
  at DocBlockrAtom.module.exports.DocBlockrAtom.parse_command (/Users/cooperm/.atom/packages/docblockr/lib/docblockr-worker.js:279:29)
  at atom-workspace.<anonymous> (/Users/cooperm/.atom/packages/docblockr/lib/docblockr-worker.js:75:16)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:238:29)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:519:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:354:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:178:20)

```

### Commands

```
     -4:26 core:save (atom-text-editor.editor.is-focused)
     -0:20.1.0 fuzzy-finder:toggle-file-finder (atom-text-editor.editor.is-focused)
     -0:19.1.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:12.7.0 refactor:done (atom-text-editor.editor.is-focused)
     -0:12.7.0 emmet:insert-formatted-line-break-only (atom-text-editor.editor.is-focused)
     -0:12.7.0 docblockr:parse-enter (atom-text-editor.editor.is-focused)
     -0:12.5.0 refactor:done (atom-text-editor.editor.is-focused)
     -0:12.5.0 emmet:insert-formatted-line-break-only (atom-text-editor.editor.is-focused)
     -0:12.5.0 docblockr:parse-enter (atom-text-editor.editor.is-focused)
     -0:12.5.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:10.7.0 refactor:done (atom-text-editor.editor.is-focused)
     -0:10.7.0 emmet:insert-formatted-line-break-only (atom-text-editor.editor.is-focused)
     -0:10.7.0 docblockr:parse-enter (atom-text-editor.editor.is-focused)
     -0:03.3.0 core:copy (atom-text-editor.editor.is-focused)
     -0:02.4.0 core:save (atom-text-editor.editor.is-focused)
  2x -0:01.1.0 core:undo (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "ignoredNames": [
      ".meteor",
      ".git",
      ".DS_Store"
    ],
    "disabledPackages": [
      "git-grep",
      "atom-prettify",
      "resize-panes",
      "themed-settings",
      "autocomplete-paths",
      "tree-view-filter",
      "letter-spacing",
      "atomatigit",
      "meteor-helper",
      "stacktrace",
      "save-session",
      "notebook",
      "scope-inspector",
      "tabs",
      "tree-view",
      "git-wip",
      "linter-eslint",
      "atom-jade",
      "vim-mode",
      "atom-lint",
      "atom-angularjs",
      "atom-bootstrap3",
      "atom-coffee-repl",
      "visual-bell",
      "view-tail-large-files",
      "atom-package-blank",
      "autocomplete-glsl",
      "term2",
      "coffee-porter",
      "figlet",
      "language-babel",
      "angularjs",
      "linter-handlebars",
      "sass-autocompile",
      "remote-atom",
      "remote-edit",
      "web-browser",
      "language-make",
      "background-tips",
      "exception-reporting",
      "language-clojure",
      "spell-check",
      "welcome",
      "autosave",
      "ever-notedown"
    ],
    "projectHome": "/Users/cooperm/sites",
    "audioBeep": false,
    "themes": [
      "one-dark-ui",
      "apathy-theme"
    ]
  },
  "docblockr": {
    "auto_add_method_tag": true,
    "per_section_indent": true,
    "lower_case_primitives": true,
    "short_primitives": true,
    "notation_map": [
      "{\"regex\":\"data$\"",
      "\"type\":\"object\"}"
    ],
    "spacer_between_sections": true
  }
}
```

### Installed Packages

```coffee
# User
ScssBundle, v0.5.0
apathy-theme, v1.1.14
atom-beautify, v0.27.6
atom-handlebars, v0.5.0
atom-jasmine, v0.5.0
atom-runner, v2.3.0
coffee-compile, v0.15.0
coffee-refactor, v0.6.2
coffeedocs, v0.8.2
color-picker, v1.7.0
comment-headers, v2.8.0
cucumber, v0.5.0
docblockr, v0.7.2
emmet, v2.3.10
file-icons, v1.5.5
file-types, v0.3.0
gist-it, v0.7.0
git-diff-details, v0.18.0
git-log, v0.3.0
js-refactor, v0.3.0
jsdoc, v0.9.0
language-jade, v0.4.0
language-javascript-semantic, v0.1.0
language-js-specs, v0.1.0
language-log, v0.4.0
language-spacebars, v0.2.2
linter, v0.12.6
linter-coffeelint, v0.2.3
linter-jscs, v1.12.0
linter-scss-lint, v1.0.4
meteor-api, v2.19.0
minimap, v4.9.0
package-sync, v0.2.0
pigments, v0.3.1
project-manager, v1.15.7
refactor, v0.4.1
script, v2.23.0
sublime-tabs, v0.5.6
syntax-settings, v0.7.1
tree-ignore, v0.2.5
turbo-javascript, v0.0.10

# Dev
apathy-theme, v1.1.14
```

**Comment by coopermaruyama** [comment]
I'll try disabling other packages and see if that helps.

**Comment by coopermaruyama** [comment]
Alright, pinpointed the issue to a setting i had for docblockr. I had the following in __Notation map__ - is this incorrect? `{"regex":"data$", "type":"object"}`

**Comment by MoritzKn** [comment]
I am closing this in an attempted to clean up the issue tracker. If this is still a bug to this day, Let me know or open a new issue.
