### ISSUE TITLE
Java: Uncaught TypeError: Cannot read property 'search' of undefined

### ISSUE THREAD

**Issue by prestontw** [nikhilkalige/docblockr#214]
Steps to reproduce:
1. Open a java program
2. Enter `/**`
3. Press `enter`

Interestingly, this does not occur when the closing mark is there; ie, if there is a `*/` on a newline, an error is not thrown. Additionally, this error is thrown for neither `/*` + `enter` nor `/***` + `enter`.

**Atom Version**: 1.9.9
**System**: linux 4.7.2-1-ARCH
**Thrown From**: [docblockr](https://github.com/nikhilkalige/docblockr) package, v0.8.4
### Stack Trace

Uncaught TypeError: Cannot read property 'search' of undefined

```
At /home/preston/.atom/packages/docblockr/lib/languages/java.js:116

TypeError: Cannot read property 'search' of undefined
    at DocsParser.JavaParser.get_definition (/home/preston/.atom/packages/docblockr/lib/languages/java.js:116:16)
    at DocBlockrAtom.module.exports.DocBlockrAtom.initialize (/home/preston/.atom/packages/docblockr/lib/docblockr-worker.js:726:26)
    at DocBlockrAtom.module.exports.DocBlockrAtom.parse_command (/home/preston/.atom/packages/docblockr/lib/docblockr-worker.js:277:12)
    at atom-workspace.<anonymous> (/home/preston/.atom/packages/docblockr/lib/docblockr-worker.js:77:16)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app.asar/src/command-registry.js:260:29)
    at /usr/share/atom/resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:580:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:388:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/usr/share/atom/resources/app.asar/src/window-event-handler.js:98:36)
    at HTMLDocument.<anonymous> (/usr/share/atom/resources/app.asar/src/window-event-handler.js:3:61)
```
### Commands

```
     -0:22.7.0 vim-mode:move-down (atom-text-editor.editor.vim-mode.is-focused.operator-pending-mode)
     -0:20.6.0 vim-mode:insert-after-end-of-line (atom-text-editor.editor.vim-mode.is-focused.normal-mode)
     -0:20.2.0 docblockr:parse-enter (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
     -0:20.2.0 editor:newline (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
  3x -0:19.5.0 core:backspace (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
  2x -0:17.8.0 docblockr:parse-enter (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
     -0:11.1.0 vim-mode:activate-normal-mode (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
  2x -0:10.8.0 vim-mode:move-down (atom-text-editor.editor.vim-mode.is-focused.normal-mode)
     -0:09.7.0 vim-mode:delete (atom-text-editor.editor.vim-mode.is-focused.normal-mode)
     -0:09.0 vim-mode:repeat-prefix (atom-text-editor.editor.vim-mode.is-focused.operator-pending-mode)
     -0:08.9.0 vim-mode:move-up (atom-text-editor.editor.vim-mode.is-focused.operator-pending-mode)
     -0:05.4.0 vim-mode:insert-below-with-newline (atom-text-editor.editor.vim-mode.is-focused.normal-mode)
     -0:02.6.0 docblockr:parse-enter (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
     -0:02.6.0 editor:newline (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
  2x -0:01.0 core:backspace (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
     -0:00.0 docblockr:parse-enter (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
```
### Config

``` json
{
  "core": {
    "themes": [
      "one-light-ui",
      "tomorrow-night-eighties-syntax"
    ]
  },
  "docblockr": {}
}
```
### Installed Packages

``` coffee
# User
autocomplete-clang, v0.9.4 (active)
build, v0.65.0 (active)
build-make, v0.11.0 (active)
busy, v0.6.0 (active)
docblockr, v0.8.4 (active)
language-docker, v1.1.7 (inactive)
language-latex, v0.6.1 (inactive)
linter, v1.11.16 (active)
linter-clang, v3.4.4 (active)
tomorrow-night-eighties-syntax, v0.16.0 (active)
vim-mode, v0.65.1 (active)
yosemate-ui, v0.7.1 (inactive)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.51.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.43.0 (inactive)
base16-tomorrow-dark-theme, v1.1.0 (inactive)
base16-tomorrow-light-theme, v1.1.1 (inactive)
one-dark-ui, v1.3.2 (inactive)
one-light-ui, v1.3.2 (active)
one-dark-syntax, v1.2.0 (inactive)
one-light-syntax, v1.2.0 (inactive)
solarized-dark-syntax, v1.0.2 (inactive)
solarized-light-syntax, v1.0.2 (inactive)
about, v1.5.2 (active)
archive-view, v0.61.1 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.11.1 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.0 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.0 (active)
bookmarks, v0.41.0 (active)
bracket-matcher, v0.82.1 (active)
command-palette, v0.38.0 (inactive)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.39.0 (active)
fuzzy-finder, v1.3.0 (active)
git-diff, v1.1.0 (active)
find-and-replace, v0.198.0 (inactive)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.1 (active)
image-view, v0.58.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.1 (inactive)
markdown-preview, v0.158.1 (active)
metrics, v0.53.1 (active)
notifications, v0.64.1 (active)
open-on-github, v1.2.0 (inactive)
package-generator, v1.0.0 (inactive)
settings-view, v0.238.2 (active)
snippets, v1.0.2 (active)
spell-check, v0.67.1 (active)
status-bar, v1.4.1 (active)
styleguide, v0.47.1 (active)
symbols-view, v0.113.0 (inactive)
tabs, v0.98.1 (active)
timecop, v0.33.1 (active)
tree-view, v0.208.0 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.34.0 (active)
whitespace, v0.32.2 (active)
wrap-guide, v0.38.1 (active)
language-c, v0.52.1 (active)
language-clojure, v0.21.0 (active)
language-coffee-script, v0.47.0 (active)
language-csharp, v0.12.1 (active)
language-css, v0.36.2 (active)
language-gfm, v0.86.0 (active)
language-git, v0.13.0 (active)
language-go, v0.42.0 (active)
language-html, v0.44.1 (active)
language-hyperlink, v0.16.0 (active)
language-java, v0.22.0 (active)
language-javascript, v0.119.0 (active)
language-json, v0.18.0 (active)
language-less, v0.29.3 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.35.0 (active)
language-php, v0.37.0 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.0 (active)
language-ruby, v0.68.5 (active)
language-ruby-on-rails, v0.25.0 (active)
language-sass, v0.52.0 (active)
language-shellscript, v0.22.3 (active)
language-source, v0.9.0 (active)
language-sql, v0.21.1 (active)
language-text, v0.7.1 (active)
language-todo, v0.28.0 (active)
language-toml, v0.18.0 (active)
language-xml, v0.34.8 (active)
language-yaml, v0.26.0 (active)

# Dev
No dev packages
```

**Comment by prestontw** [comment]
I was doing this at the bottom of the file. As long as there is something beneath the line, the error is not thrown. Strange corner case.

**Comment by vaibhav-y** [comment]
This also happens when I try using docblockr for methods which do not have method bodies or valid return types. The following code works:

```java
/**
     * [getPort description]
     * @return [description]
     */
    public int getPort() {
        
    }
```
And the following produces an error
```java
    /**
    public InetAddress getAddress()

    public String getUsername()
```
