### ISSUE TITLE
Uncaught TypeError: Cannot read property 'replace' of undefined

### ISSUE THREAD

**Issue by benargo** [nikhilkalige/docblockr#233]
[Enter steps to reproduce below:]

1. Type `/**⏎` at end of file

**Atom Version**: 1.12.6
**Electron Version**: 1.3.9
**System**: Mac OS X 10.12.1
**Thrown From**: [docblockr](https://github.com/nikhilkalige/docblockr) package, v0.9.0

### Stack Trace

Uncaught TypeError: Cannot read property 'replace' of undefined

```
At /Users/b-argo/.atom/packages/docblockr/lib/docsparser.js:353

TypeError: Cannot read property 'replace' of undefined
    at DocsParser.get_definition (/Users/b-argo/.atom/packages/docblockr/lib/docsparser.js:353:20)
    at DocBlockrAtom.module.exports.DocBlockrAtom.initialize (/Users/b-argo/.atom/packages/docblockr/lib/docblockr-worker.js:760:26)
    at DocBlockrAtom.module.exports.DocBlockrAtom.parse_command (/Users/b-argo/.atom/packages/docblockr/lib/docblockr-worker.js:276:12)
    at atom-workspace.<anonymous> (/Users/b-argo/.atom/packages/docblockr/lib/docblockr-worker.js:77:16)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:259:29)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:59
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:587:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:382:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:106:36)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:59)
```

### Commands

```
     -0:37.8.0 tree-view:add-folder (span.name.icon.icon-file-directory)
     -0:31.7.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:21.3.0 tree-view:remove (span.name.icon.icon-file-directory)
     -0:17.2.0 tree-view:add-file (span.name.icon.icon-file-directory)
     -0:09.1.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:07.3.0 autocomplete-plus:cancel (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:07.1.0 docblockr:parse-enter (atom-text-editor.editor.is-focused)
     -0:07.1.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:07.0 docblockr:parse-enter (atom-text-editor.editor.is-focused)
     -0:07.0 editor:newline (atom-text-editor.editor.is-focused)
  6x -0:02.2.0 core:backspace (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:01.1.0 docblockr:parse-enter (atom-text-editor.editor.is-focused)
     -0:01.1.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:00.9.0 docblockr:parse-enter (atom-text-editor.editor.is-focused)
     -0:00.9.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:00.0 docblockr:parse-enter (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "telemetryConsent": "no"
  }
}
```

### Installed Packages

```coffee
# User
atom-autocomplete-php, v0.20.2 (active)
atom-beautify, v0.29.13 (active)
docblockr, v0.9.0 (active)
hyperclick, v0.0.39 (active)
language-blade, v0.26.2 (active)
linter, v1.11.18 (active)
linter-php, v1.3.1 (active)
merge-conflicts, v1.4.4 (active)
minimap, v4.25.7 (active)
php-cs-fixer, v3.0.0 (active)
print-atom, v0.1.1 (inactive)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.52.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.45.0 (inactive)
base16-tomorrow-dark-theme, v1.3.0 (inactive)
base16-tomorrow-light-theme, v1.3.0 (inactive)
one-dark-ui, v1.6.2 (active)
one-light-ui, v1.6.2 (inactive)
one-dark-syntax, v1.5.0 (active)
one-light-syntax, v1.5.0 (inactive)
solarized-dark-syntax, v1.0.5 (inactive)
solarized-light-syntax, v1.0.5 (inactive)
about, v1.7.0 (active)
archive-view, v0.62.0 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.13.1 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.4 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.42.0 (active)
bracket-matcher, v0.82.2 (active)
command-palette, v0.39.0 (inactive)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.40.0 (active)
find-and-replace, v0.202.2 (inactive)
fuzzy-finder, v1.4.0 (active)
git-diff, v1.1.0 (active)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.2 (active)
image-view, v0.60.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.2 (inactive)
markdown-preview, v0.158.8 (active)
metrics, v1.1.2 (active)
notifications, v0.65.1 (active)
open-on-github, v1.2.1 (inactive)
package-generator, v1.0.1 (inactive)
settings-view, v0.243.1 (active)
snippets, v1.0.4 (active)
spell-check, v0.68.4 (active)
status-bar, v1.4.1 (active)
styleguide, v0.47.2 (active)
symbols-view, v0.113.1 (inactive)
tabs, v0.103.0 (active)
timecop, v0.33.2 (active)
tree-view, v0.210.0 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.35.1 (active)
whitespace, v0.35.0 (active)
wrap-guide, v0.38.2 (active)
language-c, v0.54.0 (active)
language-clojure, v0.22.1 (active)
language-coffee-script, v0.48.0 (active)
language-csharp, v0.13.0 (active)
language-css, v0.40.1 (active)
language-gfm, v0.88.0 (active)
language-git, v0.15.0 (active)
language-go, v0.43.0 (active)
language-html, v0.47.1 (active)
language-hyperlink, v0.16.1 (active)
language-java, v0.24.0 (active)
language-javascript, v0.122.0 (active)
language-json, v0.18.3 (active)
language-less, v0.29.6 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.37.0 (active)
language-php, v0.37.3 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.1 (active)
language-ruby, v0.70.2 (active)
language-ruby-on-rails, v0.25.1 (active)
language-sass, v0.57.0 (active)
language-shellscript, v0.23.0 (active)
language-source, v0.9.0 (active)
language-sql, v0.25.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.29.1 (active)
language-toml, v0.18.1 (active)
language-xml, v0.34.12 (active)
language-yaml, v0.27.1 (active)

# Dev
No dev packages
```

**Comment by MoritzKn** [comment]
Tanks for reporting this. This seams to be similar to #214.
Just to clarify: To reproduce this one has to enter `/**`<kbd>enter</kbd> in the very last line.

**Comment by benargo** [comment]
Correct. It's happening in PHP files for me right now. Please close if it's a duplicate.

**Comment by MoritzKn** [comment]
It's no duplicate the two issues are just similar and may be related. In #214 the exception is slightly different, it only happens for Java code and it also happens with only blank lines at the end of the file.

**Comment by mviniciusca** [comment]
It's happening in PHP files for me right now [2]

**Comment by entozoon** [comment]
Same here. Rolling back to 0.8.7 fixes it for now:
`
apm install docblockr@0.8.7
`

**Comment by nilsborchers** [comment]
Same here but inside css files

**Comment by MoritzKn** [comment]
This seems to happen for all files types.
I'm wondering why this is happening to so many people. I would assume adding `/**` to the very last line is something one wouldn't do that often. Is there another case that  causes this exception?

**Comment by MoritzKn** [comment]
Fix was released with version v0.9.1

**Comment by mviniciusca** [comment]
@MoritzKn Thanks!!

**Comment by entozoon** [comment]
@MoritzKn Thanks for the fix, FYI imagine the situation where you decide to add a new function at the end of a file and start typing a /** comment beforehand [error!]
