### ISSUE TITLE
Uncaught TypeError: Cannot read property 'name' of null

### ISSUE THREAD

**Issue by damianobarbati** [nikhilkalige/docblockr#257]
I was trying to document the following:
`getTechnicalIndicators: async ({}) => {` error
`getTechnicalIndicators: async ({ whatever }) => {` fine

The problem is when object has no members to be destructured.

1. ...
2. ...

**Atom**: 1.15.0 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.12.4
**Thrown From**: [docblockr](https://github.com/nikhilkalige/docblockr) package 0.9.4

### Stack Trace

Uncaught TypeError: Cannot read property 'name' of null

```
At /Users/damiano/.atom/packages/docblockr/lib/languages/javascript.js:164

TypeError: Cannot read property 'name' of null
    at DocsParser.JsParser.get_arg_name (/packages/docblockr/lib/languages/javascript.js:164:19)
    at DocsParser.parse_args (/packages/docblockr/lib/docsparser.js:271:48)
    at DocsParser.format_function (/packages/docblockr/lib/docsparser.js:137:32)
    at DocsParser.parse (/packages/docblockr/lib/docsparser.js:41:37)
    at DocBlockrAtom.module.exports.DocBlockrAtom.parse_command (/packages/docblockr/lib/docblockr-worker.js:286:29)
    at /packages/docblockr/lib/docblockr-worker.js:77:16)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/app.asar/src/command-registry.js:259:29)
    at /app.asar/src/command-registry.js:3:59
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:599:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:390:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/app.asar/src/window-event-handler.js:106:36)
    at /app.asar/src/window-event-handler.js:3:59)
```

### Commands

```
     -0:11.6.0 core:move-right (input.hidden-input)
     -0:11.3.0 editor:select-to-end-of-line (input.hidden-input)
     -0:11 core:copy (input.hidden-input)
     -0:06.4.0 core:move-left (input.hidden-input)
 33x -0:06.1.0 core:move-right (input.hidden-input)
     -0:04.2.0 editor:select-to-end-of-word (input.hidden-input)
     -0:03.8.0 core:select-right (input.hidden-input)
     -0:03.7.0 core:backspace (input.hidden-input)
     -0:03.2.0 core:move-up (input.hidden-input)
     -0:03.0 docblockr:parse-enter (input.hidden-input)
     -0:03.0 editor:newline (input.hidden-input)
     -0:02.9.0 docblockr:parse-tab (input.hidden-input)
     -0:02.9.0 snippets:next-tab-stop (input.hidden-input)
     -0:02.9.0 snippets:expand (input.hidden-input)
     -0:02.9.0 editor:indent (input.hidden-input)
     -0:01.8.0 docblockr:parse-enter (input.hidden-input)
```

### Non-Core Packages

```
docblockr 0.9.4 
project-manager 3.3.3 
```

**Comment by MoritzKn** [comment]
Also see #180

**Comment by ApricumMedia** [comment]
I got this exception thrown in a function using the greek letter `θ` as its second argument and initiating a doc block (typing `/**` and pressing enter).

**Comment by rafaelrpinto** [comment]
I receive the same error on a normal class method using flow-typed:

```javascript
async updateUserContext(auth0: string): Promise<any> {
...
}
```

**Comment by ChrisRast** [comment]
Same issue when trying to destructurate a parameter of a function.
```js
getClockNumber(
	{
		selected,
		type,
	},
	value
) {
	// ...
}
```

---

**Atom**: 1.19.6 x64
**Electron**: 1.6.9
**OS**: Mac OS X 10.12.6
**Thrown From**: [docblockr](https://github.com/nikhilkalige/docblockr) package 0.11.0


### Stack Trace

Uncaught TypeError: Cannot read property 'name' of null

```
At /Users/[me]/.atom/packages/docblockr/lib/languages/javascript.js:177

TypeError: Cannot read property 'name' of null
    at JsParser.get_arg_name (/packages/docblockr/lib/languages/javascript.js:177:19)
    at JsParser.DocsParser.parse_args (/packages/docblockr/lib/docsparser.js:287:48)
    at JsParser.DocsParser.format_function (/packages/docblockr/lib/docsparser.js:149:32)
    at JsParser.DocsParser.parse (/packages/docblockr/lib/docsparser.js:53:37)
    at DocBlockrAtom.module.exports.DocBlockrAtom.parse_command (/packages/docblockr/lib/docblockr-worker.js:287:29)
    at /packages/docblockr/lib/docblockr-worker.js:43:16)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:265:35)
    at /Applications/Atom.app/Contents/Resources/app/src/command-registry.js:3:65
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:610:22)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:401:28)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:100:42)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:3:65)
```

### Commands

```
  4x -5:32.5.0 docblockr:parse-tab (input.hidden-input)
  3x -5:27.3.0 core:backspace (input.hidden-input)
     -5:25.9.0 editor:delete-line (input.hidden-input)
     -5:25 core:save (input.hidden-input)
  2x -5:16.3.0 core:backspace (input.hidden-input)
     -5:09.1.0 core:save (input.hidden-input)
     -4:56.2.0 docblockr:parse-enter (input.hidden-input)
     -4:56.2.0 editor:newline (input.hidden-input)
     -4:54.6.0 docblockr:parse-tab (input.hidden-input)
     -3:54.4.0 editor:delete-line (input.hidden-input)
     -3:48.1.0 clipboard-history:copy (input.hidden-input)
     -2:59.4.0 docblockr:parse-enter (input.hidden-input)
     -2:59.4.0 editor:newline (input.hidden-input)
     -2:56.4.0 docblockr:parse-enter (input.hidden-input)
     -2:56.4.0 editor:newline (input.hidden-input)
     -2:48.9.0 clipboard-history:copy (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.30.5 
atom-handlebars 1.3.0 
atom-html-preview 0.2.2 
atom-react-autocomplete 0.1.10 
atom-spotified 0.8.2 
atom-ternjs 0.18.3 
atom-typescript 11.0.7 
autoclose-html 0.23.0 
autocomplete-html-entities 0.1.0 
autocomplete-modules 1.7.0 
busy-signal 1.4.3 
clipboard-history 0.6.6 
coffee-compile 0.26.0 
color-picker 2.2.5 
compare-files 0.8.1 
docblockr 0.11.0 
editorconfig 2.2.2 
es6-javascript 1.0.0 
escape-utils 0.5.3 
file-icons 2.1.11 
file-type-icons 1.3.4 
file-types 0.5.5 
genesis-syntax 1.0.9 
genesis-ui 0.5.0 
git-plus 7.9.3 
gl-light-syntax 3.0.0 
highlight-line 0.12.0 
hyperclick 0.1.3 
intentions 1.1.5 
js-hyperclick 1.11.0 
language-babel 2.74.1 
language-diff 0.7.0 
language-htaccess 0.1.1 
language-markdown 0.25.1 
language-nunjucks 4.1.0 
linter 2.2.0 
linter-eslint 8.2.1 
linter-js-yaml 1.2.7 
linter-php 1.4.0 
linter-remark 5.0.0 
linter-sass-lint 1.7.6 
linter-ui-default 1.6.8 
markdown-preview-plus 2.4.10 
markdown-toc 0.4.2 
minimap 4.29.6 
node-repl 0.5.0 
php-hyperclick 1.2.1 
php-twig 4.0.0 
pigments 0.40.2 
project-manager 3.3.5 
react-snippets 0.9.0 
sass-autocompile 0.13.3 
script 3.15.0 
source-preview 0.5.2 
svg-preview 0.11.0 
todo-show 2.0.0 
```

**Comment by danieleleoni** [comment]
Same problem here, any news?

**Comment by skylize** [comment]
@MoritzKn These should not cause fatal errors, essentially locking up use of the Enter key from trying create a new lines. These errors should be caught, and just revert to a basic new comment line.

**Comment by Max-Burns** [comment]
This issue exists with Hack code as well
