### ISSUE TITLE
Failed to load the docblockr package

### ISSUE THREAD

**Issue by mai1113** [nikhilkalige/docblockr#297]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.22.1 x64
**Electron**: 1.6.15
**OS**: Unknown Windows version
**Thrown From**: [docblockr](https://github.com/nikhilkalige/docblockr) package 0.13.2

### Stack Trace

Failed to load the docblockr package

```
At Cannot find module 'xregexp'

Error: Cannot find module 'xregexp'
    at Module._resolveFilename (module.js:470:15)
    at Module._resolveFilename (~/AppData/Local/atom/app-1.22.1/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (~/AppData/Local/atom/app-1.22.1/resources/app/src/module-cache.js:354:58)
    at Module.require (/app.asar/static/index.js:40:43)
    at require (~/AppData/Local/atom/app-1.22.1/resources/app/src/native-compile-cache.js:66:33)
    at /packages/docblockr-0.13.2/lib/languages/javascript.js:3:15)
    at /packages/docblockr-0.13.2/lib/languages/javascript.js:265:3)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.22.1/resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.22.1/resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (~/AppData/Local/atom/app-1.22.1/resources/app/src/native-compile-cache.js:66:33)
    at /packages/docblockr-0.13.2/lib/docblockr-worker.js:4:13)
    at /packages/docblockr-0.13.2/lib/docblockr-worker.js:1086:3)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.22.1/resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.22.1/resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (~/AppData/Local/atom/app-1.22.1/resources/app/src/native-compile-cache.js:66:33)
    at /packages/docblockr-0.13.2/lib/docblockr.js:1:178)
    at /packages/docblockr-0.13.2/lib/docblockr.js:110:3)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.22.1/resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.22.1/resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
```

### Commands

```
```

### Non-Core Packages

```
Sublime-Style-Column-Selection 1.7.4 
docblockr 0.13.2 
language-coldfusion 0.1.0 
my-package 0.0.0 
tabs-to-spaces 1.0.3 
```

**Comment by MoritzKn** [comment]
How did you install the package? Did you clone the git repository? In this case you have to run `apm install` before you can use it.

**Comment by mai1113** [comment]
I understand and succeeded to install. Thank you so much.

**Comment by Azragh** [comment]
Got the same error but installed it with atom's package manager (and everything's still working apart from the error message itself).
