### ISSUE TITLE
Uncaught TypeError: undefined is not a function

### ISSUE THREAD

**Issue by nathansizemore** [NikhilKalige/docblockr#38]
Running on linux

1. Type /**
2. Hit enter

**Atom Version**: 0.165.0
**System**: linux 3.13.0-24-generic
**Thrown From**: [docblockr](https://github.com/nikhilkalige/docblockr) package, v0.5.8

### Stack Trace

Uncaught TypeError: undefined is not a function

```
At /home/nathan/.atom/packages/docblockr/lib/docsparser.js:50

TypeError: undefined is not a function
  at DocsParser.parse (/home/nathan/.atom/packages/docblockr/lib/docsparser.js:50:16)
  at DocBlockrAtom.module.exports.DocBlockrAtom.parse_command (/home/nathan/.atom/packages/docblockr/lib/docblockr-worker.js:268:29)
  at atom-workspace.<anonymous> (/home/nathan/.atom/packages/docblockr/lib/docblockr-worker.js:64:16)
  at atom-workspace.handler (/opt/atom/resources/app/src/space-pen-extensions.js:115:32)
  at atom-workspace.jQuery.event.dispatch (/opt/atom/resources/app/node_modules/space-pen/vendor/jquery.js:4681:9)
  at atom-workspace.elemData.handle (/opt/atom/resources/app/node_modules/space-pen/vendor/jquery.js:4359:46)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/opt/atom/resources/app/src/command-registry.js:243:29)
  at /opt/atom/resources/app/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/opt/atom/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:549:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/opt/atom/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:391:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/opt/atom/resources/app/src/window-event-handler.js:167:20)

```

### Commands

```
     -0:39.1 snippets:expand (input.hidden-input)
     -0:39.1 docblockr:parse-tab (input.hidden-input)
     -0:39.1 editor:indent (input.hidden-input)
     -0:38.6 core:backspace (input.hidden-input)
     -0:36.3 core:move-down (input.hidden-input)
     -0:35.9 docblockr:parse-enter (input.hidden-input)
     -0:26.8 editor:move-to-end-of-screen-line (input.hidden-input)
  3x -0:17.7 core:backspace (input.hidden-input)
  4x -0:14.4 core:select-up (input.hidden-input)
     -0:12.9 core:select-down (input.hidden-input)
     -0:11.0 editor:select-to-first-character-of-line (input.hidden-input)
     -0:09.9 core:delete (input.hidden-input)
     -0:06.5 docblockr:parse-enter (input.hidden-input)
     -0:03.4 editor:move-to-end-of-screen-line (input.hidden-input)
     -0:00.7 core:move-down (input.hidden-input)
  2x -0:00.0 docblockr:parse-enter (input.hidden-input)
```

### Config

```
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "flatland-dark"
    ]
  }
}
```

### Installed Packages

```coffee
# User
docblockr, v0.5.8
flatland-dark, v0.1.3
language-glsl, v0.2.2
language-rust, v0.3.2
language-unity-shaderlab, v1.0.1

# Dev
No dev packages
```

/cc @atom/core

**Comment by malko** [comment]
Seems resolved with latest version. I'm closing the issue don't hesitate to re-open if you still experience the problem.

**Comment by kyhy** [comment]
1. open a java file
2. /** over code below
```
public void something() throws CustomException, IOException {}
```

**Atom Version**: 1.0.6
**System**: Mac OS X 10.9.5
**Thrown From**: [docblockr](https://github.com/nikhilkalige/docblockr) package, v0.7.3


### Stack Trace

Uncaught TypeError: undefined is not a function

```
At /Users/kyhy/.atom/packages/docblockr/lib/languages/java.js:87

TypeError: undefined is not a function
  at DocsParser.JavaParser.format_function (/Users/kyhy/.atom/packages/docblockr/lib/languages/java.js:87:84)
  at DocsParser.parse (/Users/kyhy/.atom/packages/docblockr/lib/docsparser.js:44:37)
  at DocBlockrAtom.module.exports.DocBlockrAtom.parse_command (/Users/kyhy/.atom/packages/docblockr/lib/docblockr-worker.js:279:29)
  at atom-workspace.<anonymous> (/Users/kyhy/.atom/packages/docblockr/lib/docblockr-worker.js:41:16)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:241:29)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:524:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:347:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:177:20)

```

### Commands

```
     -1:38.1.0 core:save (atom-text-editor.editor.is-focused)
     -1:29.1.0 docblockr:parse-enter (atom-text-editor.editor.is-focused)
     -1:29.1.0 editor:newline (atom-text-editor.editor.is-focused)
     -1:28 snippets:next-tab-stop (atom-text-editor.editor.is-focused)
     -1:28 snippets:expand (atom-text-editor.editor.is-focused)
     -1:28 docblockr:parse-tab (atom-text-editor.editor.is-focused)
     -1:28 editor:indent (atom-text-editor.editor.is-focused)
     -1:27.1.0 docblockr:parse-enter (atom-text-editor.editor.is-focused)
     -0:54.6.0 settings-view:open (a.btn-issue.btn.btn-error)
     -0:45.9.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:06.8.0 core:close (div.package-readme.native-key-bindings)
     -0:04.9.0 editor:select-to-first-character-of-line (atom-text-editor.editor.is-focused)
     -0:04.6.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:03.3.0 snippets:next-tab-stop (atom-text-editor.editor.is-focused)
     -0:03.3.0 snippets:expand (atom-text-editor.editor.is-focused)
     -0:03.3.0 docblockr:parse-tab (atom-text-editor.editor.is-focused)
```
