### ISSUE TITLE
TypeError: Cannot read property 'getCursors' of undefined

### ISSUE THREAD

**Issue by upgradeadvice** [nikhilkalige/docblockr#39]
This error happens when I have text selected in one pane, use a compiler or generator that creates its output in a new pane, then press enter or tab in the new pane. 

```
TypeError: Cannot read property 'getCursors' of undefined
  at DocBlockrAtom.module.exports.DocBlockrAtom.validate_request (c:\Users\James\.atom\packages\docblockr\lib\docblockr-worker.js:189:36)
  at atom-workspace.<anonymous> (c:\Users\James\.atom\packages\docblockr\lib\docblockr-worker.js:62:17)
  at atom-workspace.handler (c:\Users\James\AppData\Local\atom\app-0.169.0\resources\app\src\space-pen-extensions.js:115:32)
  at atom-workspace.jQuery.event.dispatch (c:\Users\James\AppData\Local\atom\app-0.169.0\resources\app\node_modules\space-pen\vendor\jquery.js:4681:9)
  at atom-workspace.elemData.handle (c:\Users\James\AppData\Local\atom\app-0.169.0\resources\app\node_modules\space-pen\vendor\jquery.js:4359:46)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (c:\Users\James\AppData\Local\atom\app-0.169.0\resources\app\src\command-registry.js:243:29)
  at c:\Users\James\AppData\Local\atom\app-0.169.0\resources\app\src\command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (c:\Users\James\AppData\Local\atom\app-0.169.0\resources\app\node_modules\atom-keymap\lib\keymap-manager.js:549:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (c:\Users\James\AppData\Local\atom\app-0.169.0\resources\app\node_modules\atom-keymap\lib\keymap-manager.js:391:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (c:\Users\James\AppData\Local\atom\app-0.169.0\resources\app\src\window-event-handler.js:167:20)
```

**Comment by MoritzKn** [comment]
I tried to reproduce this but I couldn't.

Steps I took:
```bash
# create two new files
touch foo.txt
touch bar.txt

# open both
atom foo.txt bar.txt

# at this point I opened both in separate panels

# wait 3 secons and write 'test' to bar.txt
sleep 3; echo 'test' >> bar.txt

# I quickly went back to atom and selected some text in the panel with foo.text
```

Everything works like expected:
Atom adds 'test' to bar.txt and <kbd>tab</kbd> just indents the text.

Could please describe more exactly what happens? maybe a GIF would help :wink:

**Comment by MoritzKn** [comment]
No response, closing. Feel free to comment here if it's still an issue.
