### ISSUE TITLE
Uncaught TypeError: Cannot read property '1' of null

### ISSUE THREAD

**Issue by cameres** [NikhilKalige/docblockr#55]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.179.0
**System**: Mac OS X 10.10.2
**Thrown From**: [docblockr](https://github.com/nikhilkalige/docblockr) package, v0.5.8

### Stack Trace

Uncaught TypeError: Cannot read property '1' of null

```
At /Users/cameres/.atom/packages/docblockr/lib/docsparser.js:538

TypeError: Cannot read property '1' of null
  at DocsParser.CppParser.get_arg_name (/Users/cameres/.atom/packages/docblockr/lib/docsparser.js:538:19)
  at DocsParser.parse_args (/Users/cameres/.atom/packages/docblockr/lib/docsparser.js:269:48)
  at DocsParser.CppParser.parse_args (/Users/cameres/.atom/packages/docblockr/lib/docsparser.js:527:44)
  at DocsParser.format_function (/Users/cameres/.atom/packages/docblockr/lib/docsparser.js:134:32)
  at DocsParser.parse (/Users/cameres/.atom/packages/docblockr/lib/docsparser.js:48:37)
  at DocBlockrAtom.module.exports.DocBlockrAtom.parse_command (/Users/cameres/.atom/packages/docblockr/lib/docblockr-worker.js:268:29)
  at atom-workspace.<anonymous> (/Users/cameres/.atom/packages/docblockr/lib/docblockr-worker.js:64:16)
  at atom-workspace.handler (/Applications/Atom.app/Contents/Resources/app/src/space-pen-extensions.js:115:32)
  at atom-workspace.jQuery.event.dispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/space-pen/vendor/jquery.js:4681:9)
  at atom-workspace.elemData.handle (/Applications/Atom.app/Contents/Resources/app/node_modules/space-pen/vendor/jquery.js:4359:46)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:243:29)
  at /Applications/Atom.app/Contents/Resources/app/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:558:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:396:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:172:20)

```

### Commands

```
     -1:52.6 snippets:expand (atom-text-editor.editor.vim-mode.autocomplete-active.insert-mode.is-focused)
     -1:52.6 editor:indent (atom-text-editor.editor.vim-mode.autocomplete-active.insert-mode.is-focused)
  5x -1:51.6 core:backspace (atom-text-editor.editor.vim-mode.autocomplete-active.insert-mode.is-focused)
     -1:48.1 docblockr:parse-enter (atom-text-editor.editor.vim-mode.autocomplete-active.insert-mode.is-focused)
 15x -1:46.4 core:backspace (atom-text-editor.editor.vim-mode.autocomplete-active.insert-mode.is-focused)
     -1:35.0 core:save (atom-text-editor.editor.vim-mode.autocomplete-active.insert-mode.is-focused)
  2x -0:37.5 docblockr:parse-enter (atom-text-editor.editor.vim-mode.autocomplete-active.insert-mode.is-focused)
  5x -0:30.2 core:backspace (atom-text-editor.editor.vim-mode.autocomplete-active.insert-mode.is-focused)
  3x -0:28.0 docblockr:parse-enter (atom-text-editor.editor.vim-mode.autocomplete-active.insert-mode.is-focused)
  3x -0:18.4 core:backspace (atom-text-editor.editor.vim-mode.autocomplete-active.insert-mode.is-focused)
     -0:17.2 core:move-down (atom-text-editor.editor.vim-mode.autocomplete-active.insert-mode.is-focused)
  3x -0:16.7 core:move-right (atom-text-editor.editor.vim-mode.autocomplete-active.insert-mode.is-focused)
  3x -0:15.9 core:backspace (atom-text-editor.editor.vim-mode.autocomplete-active.insert-mode.is-focused)
     -0:13.6 docblockr:parse-enter (atom-text-editor.editor.vim-mode.autocomplete-active.insert-mode.is-focused)
     -0:08.5 core:backspace (atom-text-editor.editor.vim-mode.autocomplete-active.insert-mode.is-focused)
  3x -0:07.6 docblockr:parse-enter (atom-text-editor.editor.vim-mode.autocomplete-active.insert-mode.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "one-dark-ui",
      "one-dark-syntax"
    ]
  },
  "docblockr": {}
}
```

### Installed Packages

```coffee
# User
autocomplete-plus, v2.1.3
docblockr, v0.5.8
file-icons, v1.4.9
jshint, v1.2.0
minimap, v4.1.4
tabs-to-spaces, v0.8.1
vim-mode, v0.31.0

# Dev
No dev packages
```

**Comment by petruavram** [comment]
This also appears for PHP in my testing: 

1. write doc block start in PHP `\**`
2. hit `Space` or `Enter`

**Atom Version**: 1.0.0
**System**: Mac OS X 10.10.3
**Thrown From**: [docblockr](https://github.com/nikhilkalige/docblockr) package, v0.7.2


### Stack Trace

Uncaught TypeError: Cannot read property '1' of null

```
At /Users/pavram/.atom/packages/docblockr/lib/languages/php.js:67

TypeError: Cannot read property '1' of null
  at DocsParser.PhpParser.get_arg_name (/Users/pavram/.atom/packages/docblockr/lib/languages/php.js:67:19)
  at DocsParser.parse_args (/Users/pavram/.atom/packages/docblockr/lib/docsparser.js:265:48)
  at DocsParser.format_function (/Users/pavram/.atom/packages/docblockr/lib/docsparser.js:130:32)
  at DocsParser.parse (/Users/pavram/.atom/packages/docblockr/lib/docsparser.js:44:37)
  at DocBlockrAtom.module.exports.DocBlockrAtom.parse_command (/Users/pavram/.atom/packages/docblockr/lib/docblockr-worker.js:279:29)
  at atom-workspace.<anonymous> (/Users/pavram/.atom/packages/docblockr/lib/docblockr-worker.js:41:16)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:241:29)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:520:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:355:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:180:20)

```

### Commands

```
  3x -0:18.8.0 core:move-up (atom-text-editor.editor.is-focused)
  4x -0:18.1.0 core:move-down (atom-text-editor.editor.is-focused)
  3x -0:16.9.0 core:move-up (atom-text-editor.editor.is-focused)
  3x -0:16 core:move-down (atom-text-editor.editor.is-focused)
     -0:06.5.0 docblockr:parse-enter (atom-text-editor.editor.is-focused)
  3x -0:05.9.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:01.4.0 docblockr:parse-tab (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "one-light-ui",
      "one-light-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
autocomplete-modules, v1.0.0
autocomplete-php, v0.3.6
autocomplete-polymer, v0.2.3
docblockr, v0.7.2
language-javascript-jsx, v0.3.6

# Dev
No dev packages
```

**Comment by petruavram** [comment]
What's worse and I forgot to mention is that going around this problem is not easy because you can't write the documentation manually as it'll keep throwing this error. I can provide a small code sample if it's necessary.

**Comment by Chais** [comment]
Still happens for C++.
Steps to reproduce:
1. Start a documentation block with '/*!' (valid for doxygen)
2. Press Enter

**Comment by stretchtiberius** [comment]
I have noticed it happens in C++ when commenting a function prototype with a 2D array parameter.

Steps to reproduce:
1.  Create function prototype with 2D array array parameter. For example, ```void x (int y [][4]);```
2.  Start a document block with ```/**```
3.  Press Enter

**Comment by vjeranc** [comment]
This also happens in C++ if definition is missing a parameter name.

```return_type ClassName::FuncName(Argument1Type &, Argument2Type &arg2);```

**Comment by octoquad** [comment]
Got this a earlier today in PHP as well.

Step 1: Create a method in a class: 
```php
<?php
class Test {
    public static function test($name, $array = ['true', '1']) { }
}
```
Step 2: Insert /** then Enter

Docblockr seems to parse the argument list correctly if you change the second method argument to:
```php
<?php
class Test {
    public static function test($name, $array = array('true', '1')) { }
}
```
Additionally Atom doesn't seem to color the second argument or anything after it. I'm not sure if that could be contributing to the problem:
![Atom Preview](https://cloud.githubusercontent.com/assets/1165755/12267562/5b7da9f4-b951-11e5-966c-409482581387.png)

Let me know if you need any more information.

**Atom Version**: 1.3.0
**System**: Ubuntu 15.10
**Thrown From**: [docblockr](https://github.com/nikhilkalige/docblockr) package, v0.7.3

### Stack Trace

Uncaught TypeError: Cannot read property '1' of null

```
At /home/bruce/dev/configs/atom/packages/docblockr/lib/languages/php.js:67

TypeError: Cannot read property '1' of null
    at DocsParser.PhpParser.get_arg_name (/home/bruce/dev/configs/atom/packages/docblockr/lib/languages/php.js:67:19)
    at DocsParser.parse_args (/home/bruce/dev/configs/atom/packages/docblockr/lib/docsparser.js:265:48)
    at DocsParser.format_function (/home/bruce/dev/configs/atom/packages/docblockr/lib/docsparser.js:130:32)
    at DocsParser.parse (/home/bruce/dev/configs/atom/packages/docblockr/lib/docsparser.js:44:37)
    at DocBlockrAtom.module.exports.DocBlockrAtom.parse_command (/home/bruce/dev/configs/atom/packages/docblockr/lib/docblockr-worker.js:279:29)
    at atom-workspace.<anonymous> (/home/bruce/dev/configs/atom/packages/docblockr/lib/docblockr-worker.js:75:16)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/opt/atom/resources/app.asar/src/command-registry.js:260:29)
    at /opt/atom/resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/opt/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:536:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/opt/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:359:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeydown (/opt/atom/resources/app.asar/src/window-event-handler.js:99:36)
    at HTMLDocument.<anonymous> (/opt/atom/resources/app.asar/src/window-event-handler.js:3:61)
```

### Commands

```
     -1:45.7.0 docblockr:parse-enter (atom-text-editor.editor.is-focused)
     -1:45.7.0 editor:newline (atom-text-editor.editor.is-focused)
     -1:45.4.0 core:save (atom-text-editor.editor.is-focused)
     -1:34.5.0 markdown-writer:indent-list-line (atom-text-editor.editor.is-focused)
     -1:34.5.0 snippets:next-tab-stop (atom-text-editor.editor.is-focused)
     -1:34.5.0 snippets:expand (atom-text-editor.editor.is-focused)
     -1:34.5.0 docblockr:parse-tab (atom-text-editor.editor.is-focused)
     -1:34.5.0 editor:indent (atom-text-editor.editor.is-focused)
     -1:34.1.0 markdown-writer:insert-new-line (atom-text-editor.editor.is-focused)
     -1:34.1.0 docblockr:parse-enter (atom-text-editor.editor.is-focused)
     -1:34.1.0 editor:newline (atom-text-editor.editor.is-focused)
     -1:33 markdown-writer:insert-new-line (atom-text-editor.editor.is-focused)
     -1:33 docblockr:parse-enter (atom-text-editor.editor.is-focused)
  3x -0:02.7.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:01.0 markdown-writer:insert-new-line (atom-text-editor.editor.is-focused)
     -0:01.0 docblockr:parse-enter (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "projectHome": "/home/bruce/dev/",
    "audioBeep": false,
    "autoHideMenuBar": true
  }
}
```

### Installed Packages

```coffee
# User
atom-alignment, v0.12.1
autocomplete-php, v0.3.7
color-picker, v2.0.14
docblockr, v0.7.3
editorconfig, v1.2.2
file-icons, v1.6.13
highlight-selected, v0.11.1
language-apache, v1.4.0
language-asciidoc, v0.12.0
language-blade, v0.16.0
language-html, v0.44.0
language-restructuredtext, v0.11.0
language-textile, v0.2.0
linter, v1.11.3
linter-csslint, v1.2.0
linter-gcc, v0.5.11
linter-jshint, v1.2.2
linter-phpcs, v1.3.0
linter-pylint, v1.2.0
linter-scss-lint, v2.5.0
linter-shellcheck, v1.1.0
linter-tidy, v1.0.1
markdown-writer, v2.2.0
meteor-api, v2.20.0
minimap, v4.19.0
pigments, v0.19.6
project-manager, v2.7.1
rst-preview-pandoc, v0.1.12
run-in-terminal, v0.5.0
symbol-gen, v1.0.0
tabs-to-spaces, v1.0.1
toggle-quotes, v1.0.0

# Dev
No dev packages
```

**Comment by stretchtiberius** [comment]
I noticed that issue is still listed as closed in spite of all the reports that it is not resolved. Are there plans for this issue to be addressed?
